version: '3.7'
services:
  api:
    build: .
    container_name: shortener-api
    ports:
      - "8080:8080"
    environment:
      - SHORTENER_USER=shortener
      - SHORTENER_PASSWORD=shortpassword
      - DB_USER=postgres
      - DB_PASS=password1234
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on: 
      - db

  db:
    image: bitnami/postgresql
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password1234
      - POSTGRESQL_DATABASE=postgres